#!/usr/bin/env ruby

# MIT License

# Copyright (C) 2020 Rizqi Nur Assyaufi <bandithijo@gmail.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

remote_repo = "bandithijo"

puts "=> Reset the master branch"
system """
git checkout master
git reset --hard origin/master
"""
puts "=> Reseting COMPLETE!"

branch_list = `git branch`
branches = branch_list.split(" ").reject{ |n| n == "*" || n == "master" }.unshift("master")

puts "\n=> Push each branch to GitHub"
for branch in branches do
  print "Pushing #{branch}... "
  `git checkout #{branch}  > /dev/null 2>&1`
  `git push -u #{remote_repo} #{branch} > /dev/null 2>&1`
  print "DONE\n"
end
`git checkout master > /dev/null 2>&1`
puts "=> All Pushing COMPLETE!"
