#!/usr/bin/env ruby

# LEGEND
# n    => branch without config
# n*   => branch with config on config branch
# n :  => branch has merge with other branch
# n <- => latest branch on the fleet

# For dwm
dwm_branches = [
  'config',
  'sticky',           # 18*
  'wasfocus',         # 19  : sticky
  'ru-gaps',          # 16* : cfacts, noborder
  'cfacts',           # 14*
  'cfacts-dragcfact', # 15* : cfacts
  'actualfullscreen', # 12* : sticky
  'xrdb',             # 2*
  'pertag',           # 1
  'noborder',         # 10
  'movestack',        # 7*
  'moveresize',       # 8*
  'resizecorners',    # 5
  'focusonnetactive', # 6
  'focusonclick',     # 23* : moveresize
  'fixborders',       # 24 <-
  'scratchpad',       # 13*
  'zoomswap',         # 3
  'savefloats',       # 4   : alwayscenter
  'alwayscenter',     # 9
  'centerkeybinding', # 20*
  'ru-bottomstack',   # 17*
  'statusallmons',    # 11
  'systray',          # 21  : zoomswap, scratchpad, wasfocus, statusallmons
  'systray-toggle'    # 22*
]

# For st
st_branches = [
  'config',
  'clipboard',
  'font2',
  'xresources',
  'workingdir',
  'boxdraw',
  'invert',
  'newterm',              # merge \w: scrollback, openclipboard, invert
  'scrollback',
  'scrollback-mouse',
  'open-copied-url',
  'bold-is-not-bright',
  'alpha',                # merge \w: boxdraw
  'ligatures-boxdraw-alpha-scrollback' # merge \w: alpha
]

# For slock
slock_branches = [
  'config',
  'capscolor',
  'message'
]

# For dmenu
dmenu_branches = [
  'config',
  'password'
]

# For tabbed
tabbed_branches = [
  'config',
  'autohide',
  'clientnumber',
  'alpha'
]

# For etc. with config branch
dir_config_branches = [
  'pinentry-dmenu',
  'slstatus',
  'sxiv'
]
config_branches = ['config']

# For etc. only master branch
dir_only_master_branches = [
  'wmname'
]
only_master_branch = ['master']

# Define dir_name based on cwd
dir_name = `basename $PWD`.strip
if dir_name == 'dwm'
  branches = dwm_branches
elsif dir_name == 'st'
  branches = st_branches
elsif dir_name == 'slock'
  branches = slock_branches
elsif dir_name == 'dmenu'
  branches = dmenu_branches
elsif dir_name == 'tabbed'
  branches = tabbed_branches
elsif dir_config_branches.include? dir_name
  branches = config_branches
elsif dir_only_master_branches.include? dir_name
  branches = only_master_branch
else
  puts 'You are not in Suckless directory!'
  exit
end

puts '=> Convert All Branch to Patch'
system 'suckdiff && git reset --hard origin/master'
puts '=> Converting COMPLETE!'

puts "\n=> Patching All Branch to Master"
branches.each do |branch|
  print "Patching #{branch}... "
  system "git merge #{branch} -m #{branch}"
  print "DONE\n"
end
puts '=> Patching COMPLETE!'

puts "\n=> Installing"
system 'make && sudo make clean install'
puts '=> Installation COMPLETE!'

if dir_name == 'dwm'
  puts """
  +----------------------------------------------------------------------+
  | STATUSBAR:                                                           |
  +----------------------------------------------------------------------+
  | Bandithijo's DWM doesn't bring the status bar.                       |
  | You should bring your own. My personal preferences are use slstatus. |
  |                                                                      |
  | Sample: https://s.id/bandithijo-slstatus                             |
  +----------------------------------------------------------------------+
  +----------------------------------------------------------------------+
  | KEYBOARD:                                                            |
  +----------------------------------------------------------------------+
  | Bandithijo's DWM doesn't bring the keyboard shortcut for apps.       |
  | You should bring your own. My personal preferences are use SXHKD.    |
  |                                                                      |
  | Sample: https://s.id/bandithijo-sxhkdrc-dwm                          |
  +----------------------------------------------------------------------+
  +----------------------------------------------------------------------+
  | AUTOSTART:                                                           |
  +----------------------------------------------------------------------+
  | BanditHijo's DWM use autostart patch. But I modified the path.       |
  | Please, provide the autostart file on:                               |
  | ~/.local/bin/autostart.sh                                            |
  |                                                                      |
  | And the other one:                                                   |
  | ~/.local/bin/autostart_blocking.sh (just empty file)                 |
  |                                                                      |
  | Don't forget to make all of them as executeable file, with:          |
  | $ chmod +x ~/.local/bin/autostart*.sh                                |
  |                                                                      |
  | Sample: https://s.id/bandithijo-autostart                            |
  +----------------------------------------------------------------------+
  """
end
