#!/usr/bin/env ruby

# For dwm
dwm_branches = [
  'config',
  'sticky', # 19
  'wasfocus', # 20 : sticky
  'ru-gaps', # 17 : cfacts, noborder
  'cfacts', # 15
  'cfacts-dragcfact', # 16 : cfacts
  'actualfullscreen', # 13 : sticky
  'xrdb', # 2
  'pertag', # 1
  'noborder', # 11
  'autostart', # 3
  'movestack', # 8
  'moveresize', # 9
  'resizecorners', # 6
  'focusonnetactive', # 7
  'focusonclick', # 24 : moveresize <-
  'scratchpad', # 14
  'zoomswap', # 4
  'savefloats', # 5 : alwayscenter
  'alwayscenter', # 10
  'centerkeybinding', # 21
  'ru-bottomstack', # 18
  'statusallmons', # 12
  'systray', # 22 : zoomswap, scratchpad, wasfocus, statusallmons
  'systray-toggle' # 23
]

# For st
st_branches = [
  'config',
  'clipboard',
  'font2',
  'xresources',
  'workingdir',
  'boxdraw',
  'invert',
  'newterm',              # merge \w: scrollback, openclipboard, invert
  'scrollback',
  'scrollback-mouse',
  'open-copied-url',
  'bold-is-not-bright',
  'alpha',                # merge \w: boxdraw
  'ligatures-boxdraw-alpha-scrollback' # merge \w: alpha
]

# For slock
slock_branches = [
  'config',
  'capscolor',
  'message'
]

# For dmenu
dmenu_branches = [
  'config',
  'password'
]

# For tabbed
tabbed_branches = [
  'config',
  'autohide',
  'clientnumber',
  'alpha'
]

# For etc. with config branch
dir_config_branches = [
  'pinentry-dmenu',
  'slstatus',
  'sxiv'
]
config_branches = ['config']

# For etc. only master branch
dir_only_master_branches = [
  'wmname'
]
only_master_branch = ['master']

# Define dir_name based on cwd
dir_name = `basename $PWD`.strip
if dir_name == 'dwm'
  branches = dwm_branches
elsif dir_name == 'st'
  branches = st_branches
elsif dir_name == 'slock'
  branches = slock_branches
elsif dir_name == 'dmenu'
  branches = dmenu_branches
elsif dir_name == 'tabbed'
  branches = tabbed_branches
elsif dir_config_branches.include? dir_name
  branches = config_branches
elsif dir_only_master_branches.include? dir_name
  branches = only_master_branch
else
  puts 'You are not in Suckless directory!'
  exit
end

puts '=> Convert All Branch to Patch'
system '''
suckdiff &&
git reset --hard origin/master
'''
puts '=> Converting COMPLETE!'

puts "\n=> Patching All Branch to Master"
branches.each do |branch|
  print "Patching #{branch}... "
  `git merge #{branch} -m #{branch}`
  print "DONE\n"
end
puts '=> Patching COMPLETE!'

puts "\n=> Installing"
system 'make && sudo make clean install'
puts '=> Installation COMPLETE!'
